name: My First work flow

on: [push]

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        -  name: checkout step
           uses: actions/checkout@v6
        -  name: list and identify files
           run: | 
            echo "My first Github action job"
            ls -ltra
            pwd
            cat README.md

        - name: Generate ASCII Command
          run: cowsay -f dragon "Run for cover , I am a dragon..." >> dragon.txt

        # -  name: List files
        #    run: ls

        # -  name: Read file
        #    run: cat README.md
        # -  name: checking current path
        #    run: pwd
        