name: Generate Ascii artwork

on: [push]

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout step
          uses: actions/checkout@v6
        - name: List files from repo
          run: ls -ltra
    
        - name: Executing shell script
          run: |
            chmod u+x ascii-script.sh
            ./ascii-script.sh
        # - name: Execute cowsay command
        #   run:  cowsay -f dragon "Run for cover , I am a dragon..." >> dragon.txt
        # - name: Test file exist
        #   run:  grep -i "dragon" dragon.txt
        # - name: Read file
        #   run: cat dragon.txt
        # - name: checkout repo files
        #   run: ls 